export const yLiquidMarketAbi = [
  {
    type: "event",
    name: "PositionOpened",
    anonymous: false,
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "adapter", type: "address", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "principal", type: "uint256", indexed: false },
      { name: "expectedDurationSeconds", type: "uint64", indexed: false },
    ],
  },
  {
    type: "function",
    name: "openPosition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "principal", type: "uint256" },
      { name: "adapter", type: "address" },
      { name: "receiver", type: "address" },
      { name: "collateralAmount", type: "uint256" },
      { name: "callbackData", type: "bytes" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "settleAndRepay",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "callbackData", type: "bytes" },
    ],
    outputs: [{ name: "amountOwed", type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteDebt",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "amountOwed", type: "uint256" }],
  },
  {
    type: "function",
    name: "availableLiquidity",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalPrincipalActive",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "rateModel",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "adapterRiskPremiumBps",
    stateMutability: "view",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [{ name: "", type: "uint32" }],
  },
  {
    type: "function",
    name: "positionNFT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "positions",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "asset", type: "address" },
      { name: "adapter", type: "address" },
      { name: "principal", type: "uint128" },
      { name: "riskPremiumBps", type: "uint32" },
      { name: "startTime", type: "uint64" },
      { name: "expectedEndTime", type: "uint64" },
      { name: "state", type: "uint8" },
    ],
  },
] as const;
