export const yLiquidAdapterUiAbi = [
  {
    type: "function",
    name: "positionView",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "receiver", type: "address" },
          { name: "proxy", type: "address" },
          { name: "loanAsset", type: "address" },
          { name: "collateralAsset", type: "address" },
          { name: "settlementAsset", type: "address" },
          { name: "principal", type: "uint256" },
          { name: "collateralAmount", type: "uint256" },
          { name: "expectedSettlementAmount", type: "uint256" },
          { name: "expectedUnlockTime", type: "uint64" },
          { name: "referenceId", type: "uint256" },
          { name: "status", type: "uint8" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "StandardizedPositionOpened",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "receiver", type: "address", indexed: true },
      { name: "loanAsset", type: "address", indexed: false },
      { name: "collateralAsset", type: "address", indexed: false },
      { name: "settlementAsset", type: "address", indexed: false },
      { name: "principal", type: "uint256", indexed: false },
      { name: "collateralAmount", type: "uint256", indexed: false },
      { name: "expectedSettlementAmount", type: "uint256", indexed: false },
      { name: "expectedUnlockTime", type: "uint64", indexed: false },
      { name: "referenceId", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StandardizedPositionClosed",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "receiver", type: "address", indexed: true },
      { name: "closeType", type: "uint8", indexed: false },
      { name: "settlementAsset", type: "address", indexed: false },
      { name: "settlementAmount", type: "uint256", indexed: false },
      { name: "repaidAmount", type: "uint256", indexed: false },
      { name: "status", type: "uint8", indexed: false },
    ],
    anonymous: false,
  },
] as const;
